let resList = [
  {
    info: {
      id: "726581",
      name: "Om Cafe",
      cloudinaryImageId: "da34f1382cb97166f2bd96653bc70e1b",
      locality: "Burja Road",
      areaName: "Vrindavan",
      costForTwo: "₹300 for two",
      cuisines: ["North Indian", "Chinese", "Snacks", "Beverages"],
      avgRating: 4.1,
      veg: true,
      parentId: "151512",
      avgRatingString: "4.1",
      totalRatingsString: "50+",
      sla: {
        deliveryTime: 43,
        lastMileTravel: 9.6,
        serviceability: "SERVICEABLE",
        slaString: "40-45 mins",
        lastMileTravelString: "9.6 km",
        iconType: "ICON_TYPE_EMPTY",
      },
      availability: {
        nextCloseTime: "2024-02-01 04:00:00",
        opened: true,
      },
      badges: {},
      isOpen: true,
      aggregatedDiscountInfoV2: {},
      type: "F",
      badgesV2: {
        entityBadges: {
          imageBased: {},
          textBased: {},
          textExtendedBadges: {},
        },
      },
      orderabilityCommunication: {
        title: {},
        subTitle: {},
        message: {},
        customIcon: {},
      },
      differentiatedUi: {
        displayType: "ADS_UI_DISPLAY_TYPE_ENUM_DEFAULT",
        differentiatedUiMediaDetails: {
          mediaType: "ADS_MEDIA_ENUM_IMAGE",
          lottie: {},
          video: {},
        },
      },
      reviewsSummary: {},
      displayType: "RESTAURANT_DISPLAY_TYPE_DEFAULT",
      restaurantOfferPresentationInfo: {},
    },
    analytics: {
      context: "seo-data-3bd1ca0b-e28a-458d-abe6-b042cfea8613",
    },
    cta: {
      link: "https://www.swiggy.com/restaurants/om-cafe-burja-road-vrindavan-mathura-726581",
      text: "RESTAURANT_MENU",
      type: "WEBLINK",
    },
    widgetId: "collectionV5RestaurantListWidget_SimRestoRelevance_food_seo",
  },

  {
    info: {
      id: "804933",
      name: "Up 78 Food Junction",
      cloudinaryImageId: "d2b3bd562cdd433230fbd5cc305e3d65",
      locality: "Burja Road",
      areaName: "Vrindavan",
      costForTwo: "₹250 for two",
      cuisines: ["Indian", "Thalis"],
      avgRating: 4.5,
      parentId: "480396",
      avgRatingString: "4.5",
      totalRatingsString: "6",
      sla: {
        deliveryTime: 44,
        lastMileTravel: 9.6,
        serviceability: "SERVICEABLE",
        slaString: "40-45 mins",
        lastMileTravelString: "9.6 km",
        iconType: "ICON_TYPE_EMPTY",
      },
      availability: {
        nextCloseTime: "2024-02-01 04:00:00",
        opened: true,
      },
      badges: {},
      isOpen: true,
      aggregatedDiscountInfoV2: {},
      type: "F",
      badgesV2: {
        entityBadges: {
          imageBased: {},
          textBased: {},
          textExtendedBadges: {},
        },
      },
      orderabilityCommunication: {
        title: {},
        subTitle: {},
        message: {},
        customIcon: {},
      },
      differentiatedUi: {
        displayType: "ADS_UI_DISPLAY_TYPE_ENUM_DEFAULT",
        differentiatedUiMediaDetails: {
          mediaType: "ADS_MEDIA_ENUM_IMAGE",
          lottie: {},
          video: {},
        },
      },
      reviewsSummary: {},
      displayType: "RESTAURANT_DISPLAY_TYPE_DEFAULT",
      isNewlyOnboarded: true,
      restaurantOfferPresentationInfo: {},
    },
    analytics: {
      context: "seo-data-3bd1ca0b-e28a-458d-abe6-b042cfea8613",
    },
    cta: {
      link: "https://www.swiggy.com/restaurants/up-78-food-junction-burja-road-vrindavan-mathura-804933",
      text: "RESTAURANT_MENU",
      type: "WEBLINK",
    },
    widgetId: "collectionV5RestaurantListWidget_SimRestoRelevance_food_seo",
  },
  {
    info: {
      id: "600497",
      name: "VIP Pizza",
      cloudinaryImageId: "a2efd0fd118fa46b6e5b194fe060460f",
      locality: "Shankar Vihar",
      areaName: "Shankar Vihar",
      costForTwo: "₹300 for two",
      cuisines: ["Italian", "North Indian", "Fast Food"],
      avgRating: 3.1,
      veg: true,
      parentId: "223889",
      avgRatingString: "3.1",
      totalRatingsString: "20+",
      sla: {
        deliveryTime: 70,
        lastMileTravel: 13.1,
        serviceability: "SERVICEABLE",
        slaString: "70-75 mins",
        lastMileTravelString: "13.1 km",
        iconType: "ICON_TYPE_EMPTY",
      },
      availability: {
        nextCloseTime: "2024-02-01 04:00:00",
        opened: true,
      },
      badges: {
        imageBadges: [
          {
            imageId: "v1695133679/badges/Pure_Veg111.png",
            description: "pureveg",
          },
        ],
      },
      isOpen: true,
      aggregatedDiscountInfoV2: {},
      type: "F",
      badgesV2: {
        entityBadges: {
          imageBased: {
            badgeObject: [
              {
                attributes: {
                  description: "pureveg",
                  imageId: "v1695133679/badges/Pure_Veg111.png",
                },
              },
            ],
          },
          textBased: {},
          textExtendedBadges: {},
        },
      },
      orderabilityCommunication: {
        title: {},
        subTitle: {},
        message: {},
        customIcon: {},
      },
      differentiatedUi: {
        displayType: "ADS_UI_DISPLAY_TYPE_ENUM_DEFAULT",
        differentiatedUiMediaDetails: {
          mediaType: "ADS_MEDIA_ENUM_IMAGE",
          lottie: {},
          video: {},
        },
      },
      reviewsSummary: {},
      displayType: "RESTAURANT_DISPLAY_TYPE_DEFAULT",
      restaurantOfferPresentationInfo: {},
    },
    analytics: {
      context: "seo-data-3bd1ca0b-e28a-458d-abe6-b042cfea8613",
    },
    cta: {
      link: "https://www.swiggy.com/restaurants/vip-pizza-shankar-vihar-mathura-600497",
      text: "RESTAURANT_MENU",
      type: "WEBLINK",
    },
    widgetId: "collectionV5RestaurantListWidget_SimRestoRelevance_food_seo",
  },
  {
    info: {
      id: "600463",
      name: "Laxmi Rasoi",
      cloudinaryImageId: "zrqmeaiycyao4ch2a8ln",
      locality: "Shankar Vihar",
      areaName: "Shankar Vihar",
      costForTwo: "₹250 for two",
      cuisines: ["North Indian"],
      avgRating: 4.1,
      veg: true,
      parentId: "276878",
      avgRatingString: "4.1",
      totalRatingsString: "10+",
      sla: {
        deliveryTime: 68,
        lastMileTravel: 13.1,
        serviceability: "SERVICEABLE",
        slaString: "65-70 mins",
        lastMileTravelString: "13.1 km",
        iconType: "ICON_TYPE_EMPTY",
      },
      availability: {
        nextCloseTime: "2024-02-01 04:00:00",
        opened: true,
      },
      badges: {},
      isOpen: true,
      type: "F",
      badgesV2: {
        entityBadges: {
          imageBased: {},
          textBased: {},
          textExtendedBadges: {},
        },
      },
      aggregatedDiscountInfoV3: {
        header: "10% OFF",
        subHeader: "UPTO ₹40",
      },
      orderabilityCommunication: {
        title: {},
        subTitle: {},
        message: {},
        customIcon: {},
      },
      differentiatedUi: {
        displayType: "ADS_UI_DISPLAY_TYPE_ENUM_DEFAULT",
        differentiatedUiMediaDetails: {
          mediaType: "ADS_MEDIA_ENUM_IMAGE",
          lottie: {},
          video: {},
        },
      },
      reviewsSummary: {},
      displayType: "RESTAURANT_DISPLAY_TYPE_DEFAULT",
      restaurantOfferPresentationInfo: {},
    },
    analytics: {
      context: "seo-data-3bd1ca0b-e28a-458d-abe6-b042cfea8613",
    },
    cta: {
      link: "https://www.swiggy.com/restaurants/laxmi-rasoi-shankar-vihar-mathura-600463",
      text: "RESTAURANT_MENU",
      type: "WEBLINK",
    },
    widgetId: "collectionV5RestaurantListWidget_SimRestoRelevance_food_seo",
  },
  {
    info: {
      id: "821073",
      name: "New Vip Pizza",
      cloudinaryImageId: "97a5dc106839dc84ae7942195d814385",
      locality: "Shankar_Vihar",
      areaName: "Shankar_Vihar",
      costForTwo: "₹300 for two",
      cuisines: ["Pizzas"],
      parentId: "7687",
      avgRatingString: "NEW",
      sla: {
        deliveryTime: 69,
        lastMileTravel: 13,
        serviceability: "SERVICEABLE",
        slaString: "65-70 mins",
        lastMileTravelString: "13.0 km",
        iconType: "ICON_TYPE_EMPTY",
      },
      availability: {
        nextCloseTime: "2024-02-01 04:00:00",
        opened: true,
      },
      badges: {},
      isOpen: true,
      aggregatedDiscountInfoV2: {},
      type: "F",
      badgesV2: {
        entityBadges: {
          imageBased: {},
          textBased: {},
          textExtendedBadges: {},
        },
      },
      orderabilityCommunication: {
        title: {},
        subTitle: {},
        message: {},
        customIcon: {},
      },
      differentiatedUi: {
        displayType: "ADS_UI_DISPLAY_TYPE_ENUM_DEFAULT",
        differentiatedUiMediaDetails: {
          mediaType: "ADS_MEDIA_ENUM_IMAGE",
          lottie: {},
          video: {},
        },
      },
      reviewsSummary: {},
      displayType: "RESTAURANT_DISPLAY_TYPE_DEFAULT",
      isNewlyOnboarded: true,
      restaurantOfferPresentationInfo: {},
    },
    analytics: {
      context: "seo-data-3bd1ca0b-e28a-458d-abe6-b042cfea8613",
    },
    cta: {
      link: "https://www.swiggy.com/restaurants/new-vip-pizza-shankar-vihar-mathura-821073",
      text: "RESTAURANT_MENU",
      type: "WEBLINK",
    },
    widgetId: "collectionV5RestaurantListWidget_SimRestoRelevance_food_seo",
  },
  {
    info: {
      id: "694761",
      name: "Radharani Rasoi",
      cloudinaryImageId: "cfe5a6b2c186e42811f595e7ebfd7331",
      locality: "West Pratap Nagar",
      areaName: "Shankar_Vihar",
      costForTwo: "₹400 for two",
      cuisines: ["Indian"],
      veg: true,
      parentId: "164221",
      avgRatingString: "--",
      sla: {
        deliveryTime: 63,
        lastMileTravel: 13.1,
        serviceability: "SERVICEABLE",
        slaString: "60-65 mins",
        lastMileTravelString: "13.1 km",
        iconType: "ICON_TYPE_EMPTY",
      },
      availability: {
        nextCloseTime: "2024-02-01 04:00:00",
        opened: true,
      },
      badges: {},
      isOpen: true,
      aggregatedDiscountInfoV2: {},
      type: "F",
      badgesV2: {
        entityBadges: {
          imageBased: {},
          textBased: {},
          textExtendedBadges: {},
        },
      },
      orderabilityCommunication: {
        title: {},
        subTitle: {},
        message: {},
        customIcon: {},
      },
      differentiatedUi: {
        displayType: "ADS_UI_DISPLAY_TYPE_ENUM_DEFAULT",
        differentiatedUiMediaDetails: {
          mediaType: "ADS_MEDIA_ENUM_IMAGE",
          lottie: {},
          video: {},
        },
      },
      reviewsSummary: {},
      displayType: "RESTAURANT_DISPLAY_TYPE_DEFAULT",
      restaurantOfferPresentationInfo: {},
    },
    analytics: {
      context: "seo-data-3bd1ca0b-e28a-458d-abe6-b042cfea8613",
    },
    cta: {
      link: "https://www.swiggy.com/restaurants/radharani-rasoi-west-pratap-nagar-shankar-vihar-mathura-694761",
      text: "RESTAURANT_MENU",
      type: "WEBLINK",
    },
    widgetId: "collectionV5RestaurantListWidget_SimRestoRelevance_food_seo",
  },
  {
    info: {
      id: "821185",
      name: "The Vip Pizza",
      cloudinaryImageId: "910b43a11f7d0051cba0a680eb73a689",
      locality: "Shankar_Vihar",
      areaName: "Shankar_Vihar",
      costForTwo: "₹250 for two",
      cuisines: ["Burgers"],
      parentId: "489969",
      avgRatingString: "NEW",
      sla: {
        deliveryTime: 62,
        lastMileTravel: 13,
        serviceability: "SERVICEABLE",
        slaString: "60-65 mins",
        lastMileTravelString: "13.0 km",
        iconType: "ICON_TYPE_EMPTY",
      },
      availability: {
        nextCloseTime: "2024-02-01 04:00:00",
        opened: true,
      },
      badges: {},
      isOpen: true,
      aggregatedDiscountInfoV2: {},
      type: "F",
      badgesV2: {
        entityBadges: {
          imageBased: {},
          textBased: {},
          textExtendedBadges: {},
        },
      },
      orderabilityCommunication: {
        title: {},
        subTitle: {},
        message: {},
        customIcon: {},
      },
      differentiatedUi: {
        displayType: "ADS_UI_DISPLAY_TYPE_ENUM_DEFAULT",
        differentiatedUiMediaDetails: {
          mediaType: "ADS_MEDIA_ENUM_IMAGE",
          lottie: {},
          video: {},
        },
      },
      reviewsSummary: {},
      displayType: "RESTAURANT_DISPLAY_TYPE_DEFAULT",
      isNewlyOnboarded: true,
      restaurantOfferPresentationInfo: {},
    },
    analytics: {
      context: "seo-data-3bd1ca0b-e28a-458d-abe6-b042cfea8613",
    },
    cta: {
      link: "https://www.swiggy.com/restaurants/the-vip-pizza-shankar-vihar-mathura-821185",
      text: "RESTAURANT_MENU",
      type: "WEBLINK",
    },
    widgetId: "collectionV5RestaurantListWidget_SimRestoRelevance_food_seo",
  },
  {
    info: {
      id: "732504",
      name: "Shri Krishna paratha Junction",
      cloudinaryImageId: "ee4131fd2ba063b8fe1b815586d1fe83",
      locality: "M10 SHRI RADHA FLORENCE",
      areaName: "Mat_Vrindavan",
      costForTwo: "₹500 for two",
      cuisines: ["Indian"],
      veg: true,
      parentId: "435000",
      avgRatingString: "--",
      sla: {
        deliveryTime: 83,
        lastMileTravel: 9.5,
        serviceability: "SERVICEABLE_WITH_BANNER",
        slaString: "80-85 mins",
        lastMileTravelString: "9.5 km",
        iconType: "ICON_TYPE_EMPTY",
      },
      availability: {
        nextOpenTimeMessage: "Opens next at 11 am, today",
      },
      badges: {
        imageBadges: [
          {
            imageId: "v1695133679/badges/Pure_Veg111.png",
            description: "pureveg",
          },
        ],
      },
      aggregatedDiscountInfoV2: {},
      type: "F",
      badgesV2: {
        entityBadges: {
          imageBased: {
            badgeObject: [
              {
                attributes: {
                  description: "pureveg",
                  imageId: "v1695133679/badges/Pure_Veg111.png",
                },
              },
            ],
          },
          textBased: {},
          textExtendedBadges: {},
        },
      },
      orderabilityCommunication: {
        title: {},
        subTitle: {},
        message: {},
        customIcon: {},
      },
      differentiatedUi: {
        displayType: "ADS_UI_DISPLAY_TYPE_ENUM_DEFAULT",
        differentiatedUiMediaDetails: {
          mediaType: "ADS_MEDIA_ENUM_IMAGE",
          lottie: {},
          video: {},
        },
      },
      reviewsSummary: {},
      displayType: "RESTAURANT_DISPLAY_TYPE_DEFAULT",
      restaurantOfferPresentationInfo: {},
    },
    analytics: {
      context: "seo-data-3bd1ca0b-e28a-458d-abe6-b042cfea8613",
    },
    cta: {
      link: "https://www.swiggy.com/restaurants/shri-krishna-paratha-junction-m10-shri-radha-florence-mat-vrindavan-mathura-732504",
      text: "RESTAURANT_MENU",
      type: "WEBLINK",
    },
    widgetId: "collectionV5RestaurantListWidget_SimRestoRelevance_food_seo",
  },
  {
    info: {
      id: "753052",
      name: "Delicious Food Court",
      cloudinaryImageId: "5720a388780f942358aa80f1f4f58202",
      locality: "Gaura Nagar Colony",
      areaName: "Vrindavan",
      costForTwo: "₹200 for two",
      cuisines: ["North Indian", "Indian"],
      avgRating: 4.5,
      veg: true,
      parentId: "70380",
      avgRatingString: "4.5",
      totalRatingsString: "50+",
      sla: {
        deliveryTime: 51,
        lastMileTravel: 11.1,
        serviceability: "SERVICEABLE",
        slaString: "50-55 mins",
        lastMileTravelString: "11.1 km",
        iconType: "ICON_TYPE_EMPTY",
      },
      availability: {
        nextOpenTimeMessage: "Opens next at 8 am, today",
      },
      badges: {},
      aggregatedDiscountInfoV2: {},
      type: "F",
      badgesV2: {
        entityBadges: {
          imageBased: {},
          textBased: {},
          textExtendedBadges: {},
        },
      },
      orderabilityCommunication: {
        title: {},
        subTitle: {},
        message: {},
        customIcon: {},
      },
      differentiatedUi: {
        displayType: "ADS_UI_DISPLAY_TYPE_ENUM_DEFAULT",
        differentiatedUiMediaDetails: {
          mediaType: "ADS_MEDIA_ENUM_IMAGE",
          lottie: {},
          video: {},
        },
      },
      reviewsSummary: {},
      displayType: "RESTAURANT_DISPLAY_TYPE_DEFAULT",
      isNewlyOnboarded: true,
      restaurantOfferPresentationInfo: {},
    },
    analytics: {
      context: "seo-data-3bd1ca0b-e28a-458d-abe6-b042cfea8613",
    },
    cta: {
      link: "https://www.swiggy.com/restaurants/delicious-food-court-gaura-nagar-colony-vrindavan-mathura-753052",
      text: "RESTAURANT_MENU",
      type: "WEBLINK",
    },
    widgetId: "collectionV5RestaurantListWidget_SimRestoRelevance_food_seo",
  },
];
export default resList;
